os: linux
dist: xenial
language: python
before_install:
- pip install --upgrade pip wheel setuptools codecov
install:
- pip install -r requirements.txt
script:
- tox
jobs:
  include:
  - python: '3.5'
    env: TOXENV=py35-django220
  - python: '3.6'
    env: TOXENV=py36-django220
  - python: '3.6'
    env: TOXENV=py36-django300
  - python: '3.7'
    env: TOXENV=py37-django220
  - python: '3.7'
    env: TOXENV=py37-django300
  - python: '3.8'
    env: TOXENV=py38-django220
  - python: '3.8'
    env: TOXENV=py38-django300
after_success:
- codecov
